export interface ConfirmacionMensaje {
    msjTipo: number;
    titulo:  String;
    mensaje: String;
    detalle: String;
  }

  // Generated by https://quicktype.io
export interface listados {
  id:          Number;
  descripcion: String;
}

// busqueda del proveedor
export interface DataNombreMDL {
  tabla:   String;
  nombre:   String;
  rfc:      String;
  codigo:   String;
}



